package template

import (
	"bytes"
	"fmt"
	"strings"
	"time"
)

// ZoneRecord represents a single DNS resource record in a BIND9 zone file.
type ZoneRecord struct {
	Name     string // record name (e.g., "@", "www", "mail")
	TTL      int    // time-to-live in seconds
	Class    string // always "IN"
	Type     string // A, AAAA, CNAME, MX, TXT, NS, SOA, SRV, CAA
	Priority int    // used for MX and SRV records
	Value    string // record value
}

// ZoneFileData holds all data needed to render a BIND9 zone file.
type ZoneFileData struct {
	Domain  string
	Records []ZoneRecord
}

// generateSerial creates a YYYYMMDDNN-style serial number.
// Uses current date plus a nanosecond-derived counter (00-99) to avoid
// collisions when multiple zone updates happen on the same day.
// Note: fits in a 32-bit unsigned SOA serial until year 4294 (max 4294967295).
func generateSerial() string {
	now := time.Now().UTC()
	// Use last 2 digits of nanosecond as NN counter — good enough to avoid
	// same-second collisions in practice.
	nn := now.Nanosecond() / 10_000_000 // 0-99
	return fmt.Sprintf("%s%02d", now.Format("20060102"), nn)
}

// RenderZoneFile renders a BIND9 zone file from the given data.
// SOA is always rendered first (required by BIND), then NS, then the rest.
func RenderZoneFile(data ZoneFileData) (string, error) {
	var buf bytes.Buffer
	serial := generateSerial()

	buf.WriteString(fmt.Sprintf("; Zone file for %s\n", data.Domain))
	buf.WriteString(fmt.Sprintf("; Generated by PinkPanel at %s\n", time.Now().Format(time.RFC3339)))
	buf.WriteString(fmt.Sprintf("$TTL 3600\n$ORIGIN %s.\n\n", data.Domain))

	// 1. SOA — find mname/rname from records, or use defaults
	soaValue := fmt.Sprintf("ns1.%s. admin.%s.", data.Domain, data.Domain)
	for _, r := range data.Records {
		if r.Type == "SOA" && r.Value != "" {
			soaValue = r.Value
			break
		}
	}

	buf.WriteString(fmt.Sprintf("@\tIN\tSOA\t%s (\n", soaValue))
	buf.WriteString(fmt.Sprintf("\t\t\t\t%s\t; serial\n", serial))
	buf.WriteString("\t\t\t\t3600\t\t; refresh (1 hour)\n")
	buf.WriteString("\t\t\t\t900\t\t; retry (15 minutes)\n")
	buf.WriteString("\t\t\t\t1209600\t\t; expire (2 weeks)\n")
	buf.WriteString("\t\t\t\t86400 )\t\t; minimum (1 day)\n\n")

	// 2. NS records
	for _, r := range data.Records {
		if r.Type == "NS" {
			buf.WriteString(fmt.Sprintf("%s\t%d\tIN\tNS\t%s\n", r.Name, r.TTL, r.Value))
		}
	}
	buf.WriteString("\n")

	// 3. All other records (skip SOA and NS, already rendered)
	for _, r := range data.Records {
		if r.Type == "SOA" || r.Type == "NS" {
			continue
		}
		buf.WriteString(renderRecord(r))
		buf.WriteString("\n")
	}

	return buf.String(), nil
}

// renderRecord formats a single ZoneRecord as a BIND9 zone file line.
func renderRecord(r ZoneRecord) string {
	switch r.Type {
	case "MX":
		return fmt.Sprintf("%s\t%d\tIN\tMX\t%d\t%s",
			r.Name, r.TTL, r.Priority, r.Value)
	case "SRV":
		return fmt.Sprintf("%s\t%d\tIN\tSRV\t%d\t%s",
			r.Name, r.TTL, r.Priority, r.Value)
	case "TXT":
		return fmt.Sprintf("%s\t%d\tIN\tTXT\t%s",
			r.Name, r.TTL, formatTXT(r.Value))
	default:
		return fmt.Sprintf("%s\t%d\tIN\t%s\t%s",
			r.Name, r.TTL, r.Type, r.Value)
	}
}

// formatTXT formats a TXT record value for BIND zone files.
// BIND limits each quoted string to 255 characters, so longer values
// (e.g. DKIM keys) must be split into multiple quoted chunks.
func formatTXT(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")

	if len(s) <= 255 {
		return fmt.Sprintf("\"%s\"", s)
	}

	// Split into 255-char chunks wrapped in parentheses
	var parts []string
	for len(s) > 0 {
		end := 255
		if end > len(s) {
			end = len(s)
		}
		parts = append(parts, fmt.Sprintf("\"%s\"", s[:end]))
		s = s[end:]
	}
	return "( " + strings.Join(parts, " ") + " )"
}
